// Generated by CoffeeScript 1.3.1
(function() {
  var express, fs, github, keys, read, rem;

  rem = require('../rem');

  fs = require('fs');

  read = require('read');

  express = require('express');

  keys = JSON.parse(fs.readFileSync(__dirname + '/keys.json'));

  github = rem.load('github', '1', {
    key: keys.github.key,
    secret: keys.github.secret
  });

  rem.oauthConsole(github, {
    scope: ["user", "repo"]
  }, function(err, user) {
    console.log('Your gists:');
    return user('user').get(function(err, profile) {
      return user("users/" + profile.login + "/gists").get(function(err, json) {
        var gist, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = json.length; _i < _len; _i++) {
          gist = json[_i];
          _results.push(console.log(' -', gist.description));
        }
        return _results;
      });
    });
  });

}).call(this);
