// Generated by CoffeeScript 1.3.1
(function() {
  var example, fs, keys, read, reddit, rem, session;

  rem = require('../rem');

  fs = require('fs');

  read = require('read');

  keys = JSON.parse(fs.readFileSync(__dirname + '/keys.json'));

  reddit = rem.load('reddit', '1');

  session = rem.session(reddit);

  read({
    prompt: 'Username: '
  }, function(err, user) {
    return read({
      prompt: 'Password: ',
      silent: true
    }, function(err, password) {
      return session.authenticate(user, password, example);
    });
  });

  example = function(err, user) {
    if (err) {
      console.log(err);
      return;
    }
    return user('api/me').get(function(err, json) {
      if (err) {
        console.log(err);
        return;
      }
      return console.log('Your account:', JSON.stringify(json, null, '  '));
    });
  };

}).call(this);
