// Generated by CoffeeScript 1.3.1
(function() {
  var express, fs, keys, read, rem, tumblr;

  rem = require('../rem');

  fs = require('fs');

  read = require('read');

  express = require('express');

  keys = JSON.parse(fs.readFileSync(__dirname + '/keys.json'));

  tumblr = rem.load('tumblr', '2', {
    key: keys.tumblr.key
  });

  tumblr('blog/staff.tumblr.com/posts/text').get(function(err, json) {
    return console.log(json.response.blog.title + ' - ' + json.response.blog.description);
  });

}).call(this);
