// Generated by CoffeeScript 1.3.1
(function() {
  var fs, keys, read, rem, yt;

  rem = require('../rem');

  fs = require('fs');

  read = require('read');

  keys = JSON.parse(fs.readFileSync(__dirname + '/keys.json'));

  yt = rem.load('youtube', '2', {
    key: keys.youtube.key,
    secret: keys.youtube.secret,
    devkey: keys.youtube.devkey,
    format: 'xml'
  });

  rem.oauthConsole(yt, function(err, user) {
    return user('users/default').get(function(err, xml) {
      var prop, _i, _len, _ref, _results;
      if (err) {
        console.error(err);
        return;
      }
      console.log('Your profile: (error', err, ')');
      _ref = xml.find('/a:entry/*', {
        a: "http://www.w3.org/2005/Atom"
      });
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        prop = _ref[_i];
        if (prop.text()) {
          _results.push(console.log(' -', prop.name() + ':', prop.text()));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
  });

}).call(this);
